SetPowerNode "VDD"
SetGroundNode "VSS"
SetLibraryCorner "all"
SetSlewMode "all"
ReadGCFTimingLibraries "gcfConstraints.gcf"
ReadSPFNetlist "top.spf"
ReadGCFConstraints "gcfConstraints.gcf"
ReadSPF "top.spf"
WriteSDFDelays -delimiter "." -edge_specifier -version 3.0 -ns -precision 4 "top.tmp.sdf"
